### PR TITLE
add automatic markdown linting and formatting

### PR DESCRIPTION
**Pull request by boneskull**
several things make this happen:

- `husky` for installing pre-commit hooks
- `lint-staged` for performing operations on _only staged files_; run as pre-commit hook
- `prettier` for formatting the markdown sensibly
- `markdownlint-cli2` for other concerns not addressed by prettier

The `markdownlint-cli2` executable provides linting (`npm run lint:markdown`) and the `markdownlint-cli2-fix` executable fixes problems (_that it can_ fix -- like `eslint --fix`) via `npm run format`.  `npm run format` runs both `prettier` and `markdownlint-cli2-fix`.

fix: modified Hugo config to allow raw HTML (in some circumstances), which was previously broken.  note that there seems to be a bug in Hugo where raw html will render only on first build of a development server.  subsequent builds will strip the html.

### CODE REVIEW

**Review by christian-bromann — DISMISSED** [review]
LGTM 👍

**Comment by boneskull** [comment]
for reviewers, please take a quick look at the site preview.  there should be no difference in display (aside from a bug on the `devtools_ui.md` page), but you never know...

**Review by diemol — DISMISSED** [review]
👍

**Comment by boneskull** [comment]
@diemol I'd like you to take a gander at the netlify configuration.  It was failing because:

1. it was running `update:sw` which now expects a `GITHUB_RUN_NUMBER` env var, which does not exist on Netlify.
2. further, it was running a script called `build:netlify` which no longer exists.

I'm not sure what happened here--or why recent PRs have seemingly passed all of the checks--if this was broken

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* dev
  * **PR #89**  (this PR)
    * **PR #93** 

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh) and will continue to be automatically updated while this PR remains open.

**Pull request merged**
